services:
  - type: web
    name: movieflix-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node backend/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.19.4
      - key: TMDB_API_KEY
        sync: false
