org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.parallel=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
android.enableProfileEmbedding=false
android.enableResourceOptimizations=false
android.experimental.enableProfileEmbedding=false
android.enableProfileEmbedding=false
android.baselineProfile.enable=false
