org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=160m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.parallel=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx256m
android.enableProfileEmbedding=false
